AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: Build on AWS DB Tier Stack.
Parameters:
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  DBSecurityGroup:
    Type: String
  DBPassword:
    NoEcho: 'true'
    Type: String
    Description: New account and RDS password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupName: MyDBSubnetGroup
      DBSubnetGroupDescription: MyDBSubnetGroup
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  MyDB: 
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties: 
      DBInstanceIdentifier: edx-photos-db
      DBName: Photos
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      BackupRetentionPeriod: 0
      MasterUsername: master
      MasterUserPassword: 
        Ref: DBPassword
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      DBSecurityGroups:
        - !Ref DBSecurityGroup

Outputs:
  MyDBEndpoint:
    Value: !GetAtt MyDB.Endpoint.Address
    Description: MyDB Endpoint
