AWSTemplateFormatVersion: '2010-09-09'
Description: Building on AWS Web Server Stack
Parameters:
  SourceBucket:
    Type: String
  EC2VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  WebServerInstanceProfile:
    Type: String
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  LoadBalancerArn:
    Type: String
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2
Resources:
  WebInstance1: 
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          InstallAndRun:
            - Install
            - Configure
        Install:      
          packages:
            yum:
              python36: []
              python36-devel: []
              nginx: []
              gcc: []
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets InstallAndRun --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: root
              group: root                

          services:
            sysvinit:
              nginx:
                enabled: 'true'
                ensureRunning: 'true'
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
        Configure:
          commands:
            set_source_bucket:
              command: !Sub |
                export bucket=${SourceBucket}
            deploy:
              command: !Sub |
                pip-3.6 install uwsgi
                
                # download and setup our application
                mkdir /photos
                cd /photos
                aws s3 cp s3://$bucket/deploy-app.zip .
                unzip deploy-app.zip
                pip-3.6 install -r FlaskApp/requirements.txt
                # copy in the nginx config
                mv -f Deploy/nginx.conf /etc/nginx/nginx.conf
                # configure upstart to run uwsgi
                mv -f Deploy/uwsgi.conf /etc/init/uwsgi.conf
            create_db:
              command: !Sub |  
                python3 Deploy/database_create_tables.py
            start_uwsgi:
              command: !Sub |
                start uwsgi
                # switch on nginx and configure to autostart
                chkconfig nginx on
                service nginx restart
            x_ray:
              command: !Sub |
                curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
                yum install -y /home/ec2-user/xray.rpm
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      IamInstanceProfile: !Ref WebServerInstanceProfile
      NetworkInterfaces: 
        -   
          DeviceIndex: 0
          GroupSet: 
            - Ref: WebSecurityGroup
          SubnetId: 
            Ref: PrivateSubnet1
      Tags:
        -
          Key: Name
          Value: WebServer1
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          yum update -y
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebInstance1 --configsets InstallAndRun --region ${AWS::Region}
          # Signal the status from cfn-init (via $?)
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebInstance1 --region ${AWS::Region}
        
  WebInstance2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      IamInstanceProfile: !Ref WebServerInstanceProfile
      NetworkInterfaces: 
        - 
          DeviceIndex: 0
          GroupSet: 
            - Ref: WebSecurityGroup
          SubnetId: 
            Ref: PrivateSubnet2
      Tags:
        -
          Key: Name
          Value: WebServer2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          bucket=${SourceBucket}
          
          yum -y update
          
          # install python3.6 and dev tools
          yum -y install python36
          yum -y install python36-devel
          
          # install nginx
          yum -y install nginx
          
          # install the uwsgi server
          yum -y install gcc
          pip-3.6 install uwsgi
          
          # download and setup our application
          mkdir /photos
          cd /photos
          aws s3 cp s3://$bucket/deploy-app.zip .
          unzip deploy-app.zip
          pip-3.6 install -r FlaskApp/requirements.txt
          
          python3 Deploy/database_create_tables.py
          
          # copy in the nginx config
          mv -f Deploy/nginx.conf /etc/nginx/nginx.conf
          # configure upstart to run uwsgi
          mv -f Deploy/uwsgi.conf /etc/init/uwsgi.conf
          start uwsgi
          
          # switch on nginx and configure to autostart
          chkconfig nginx on
          service nginx start
          curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
          yum install -y /home/ec2-user/xray.rpm
  DefaultTargetGroup: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: '/'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref EC2VpcId
      TargetGroupAttributes:
        -   
          Key: deregistration_delay.timeout_seconds
          Value: 30        
      Targets:
        - Id: !Ref WebInstance1
          Port: 80
        - Id: !Ref WebInstance2
          Port: 80
            
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DefaultTargetGroup
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 80
      Protocol: HTTP
